/**
 * Generated by scripts/generate-database-types.mjs from local disposable Supabase instance.
 * DO NOT EDIT MANUALLY. Run `npm run typegen:supabase` to regenerate.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      agencies: {
        Row: {
          created_at: string
          email: string | null
          id: string
          name: string
          phone: string | null
        }
        Insert: {
          created_at?: string
          email?: string | null
          id?: string
          name: string
          phone?: string | null
        }
        Update: {
          created_at?: string
          email?: string | null
          id?: string
          name?: string
          phone?: string | null
        }
        Relationships: []
      }
      auth_login_attempts: {
        Row: {
          created_at: string
          email_key: string
          failed_count: number
          ip_key: string
          last_failed_at: string | null
          locked_until: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          email_key: string
          failed_count?: number
          ip_key: string
          last_failed_at?: string | null
          locked_until?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          email_key?: string
          failed_count?: number
          ip_key?: string
          last_failed_at?: string | null
          locked_until?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      owners: {
        Row: {
          created_at: string
          email: string | null
          id: string
          name: string
          phone: string | null
        }
        Insert: {
          created_at?: string
          email?: string | null
          id?: string
          name: string
          phone?: string | null
        }
        Update: {
          created_at?: string
          email?: string | null
          id?: string
          name?: string
          phone?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          address: string | null
          birth_date: string | null
          created_at: string
          email: string
          full_name: string
          hourly_rate: number | null
          id: string
          monthly_salary: number | null
          nationality: string | null
          overtime_rate: number | null
          phone: string | null
          role: string
        }
        Insert: {
          address?: string | null
          birth_date?: string | null
          created_at?: string
          email: string
          full_name: string
          hourly_rate?: number | null
          id: string
          monthly_salary?: number | null
          nationality?: string | null
          overtime_rate?: number | null
          phone?: string | null
          role?: string
        }
        Update: {
          address?: string | null
          birth_date?: string | null
          created_at?: string
          email?: string
          full_name?: string
          hourly_rate?: number | null
          id?: string
          monthly_salary?: number | null
          nationality?: string | null
          overtime_rate?: number | null
          phone?: string | null
          role?: string
        }
        Relationships: []
      }
      properties: {
        Row: {
          address: string | null
          agency_id: string | null
          armchair_beds: number | null
          avg_cleaning_hours: number | null
          base_price: number | null
          bathrooms: number | null
          bedrooms: number | null
          bidets: number | null
          client_type: string
          created_at: string
          cribs: number | null
          double_beds: number | null
          email: string | null
          extra_per_person: number | null
          id: string
          max_guests: number | null
          min_guests: number | null
          name: string
          notes: string | null
          owner_id: string | null
          phone: string | null
          single_beds: number | null
          sofa_beds: number | null
          sqm_exterior: number | null
          sqm_interior: number | null
          sqm_total: number | null
          zip_code: string | null
          zone: string
        }
        Insert: {
          address?: string | null
          agency_id?: string | null
          armchair_beds?: number | null
          avg_cleaning_hours?: number | null
          base_price?: number | null
          bathrooms?: number | null
          bedrooms?: number | null
          bidets?: number | null
          client_type: string
          created_at?: string
          cribs?: number | null
          double_beds?: number | null
          email?: string | null
          extra_per_person?: number | null
          id?: string
          max_guests?: number | null
          min_guests?: number | null
          name: string
          notes?: string | null
          owner_id?: string | null
          phone?: string | null
          single_beds?: number | null
          sofa_beds?: number | null
          sqm_exterior?: number | null
          sqm_interior?: number | null
          sqm_total?: number | null
          zip_code?: string | null
          zone: string
        }
        Update: {
          address?: string | null
          agency_id?: string | null
          armchair_beds?: number | null
          avg_cleaning_hours?: number | null
          base_price?: number | null
          bathrooms?: number | null
          bedrooms?: number | null
          bidets?: number | null
          client_type?: string
          created_at?: string
          cribs?: number | null
          double_beds?: number | null
          email?: string | null
          extra_per_person?: number | null
          id?: string
          max_guests?: number | null
          min_guests?: number | null
          name?: string
          notes?: string | null
          owner_id?: string | null
          phone?: string | null
          single_beds?: number | null
          sofa_beds?: number | null
          sqm_exterior?: number | null
          sqm_interior?: number | null
          sqm_total?: number | null
          zip_code?: string | null
          zone?: string
        }
        Relationships: [
          {
            foreignKeyName: "properties_agency_id_fkey"
            columns: ["agency_id"]
            isOneToOne: false
            referencedRelation: "agencies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "properties_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "owners"
            referencedColumns: ["id"]
          },
        ]
      }
      service_order_cleaning_staff: {
        Row: {
          created_at: string
          profile_id: string
          service_order_id: string
        }
        Insert: {
          created_at?: string
          profile_id: string
          service_order_id: string
        }
        Update: {
          created_at?: string
          profile_id?: string
          service_order_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_order_cleaning_staff_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_order_cleaning_staff_service_order_id_fkey"
            columns: ["service_order_id"]
            isOneToOne: false
            referencedRelation: "service_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      service_order_photos: {
        Row: {
          content_type: string
          created_at: string
          cycle_no: number
          display_path: string
          display_size_bytes: number | null
          height: number | null
          id: string
          phase: string
          ready_at: string | null
          service_order_id: string
          sort_order: number
          status: string
          thumbnail_path: string
          thumbnail_size_bytes: number | null
          uploaded_by: string | null
          width: number | null
        }
        Insert: {
          content_type?: string
          created_at?: string
          cycle_no: number
          display_path: string
          display_size_bytes?: number | null
          height?: number | null
          id?: string
          phase: string
          ready_at?: string | null
          service_order_id: string
          sort_order: number
          status?: string
          thumbnail_path: string
          thumbnail_size_bytes?: number | null
          uploaded_by?: string | null
          width?: number | null
        }
        Update: {
          content_type?: string
          created_at?: string
          cycle_no?: number
          display_path?: string
          display_size_bytes?: number | null
          height?: number | null
          id?: string
          phase?: string
          ready_at?: string | null
          service_order_id?: string
          sort_order?: number
          status?: string
          thumbnail_path?: string
          thumbnail_size_bytes?: number | null
          uploaded_by?: string | null
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "service_order_photos_service_order_id_fkey"
            columns: ["service_order_id"]
            isOneToOne: false
            referencedRelation: "service_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_order_photos_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      service_orders: {
        Row: {
          armchair_beds: number | null
          bathrooms: number | null
          bedrooms: number | null
          bidets: number | null
          checkin_at: string | null
          checkout_at: string | null
          cleaning_cycle: number
          cleaning_date: string | null
          cleaning_notes: string | null
          cleaning_staff_id: string | null
          completed_at: string | null
          completion_notes: string | null
          consegna_fee: number
          consegna_staff_id: string | null
          created_at: string
          cribs: number | null
          double_beds: number | null
          extra_services_description: string | null
          extra_services_price: number | null
          id: string
          is_urgent: boolean | null
          order_number: number | null
          pricing_mode: string
          property_id: string
          real_guests: number | null
          single_beds: number | null
          sofa_beds: number | null
          started_at: string | null
          status: string
          total_price: number | null
          worked_minutes: number | null
        }
        Insert: {
          armchair_beds?: number | null
          bathrooms?: number | null
          bedrooms?: number | null
          bidets?: number | null
          checkin_at?: string | null
          checkout_at?: string | null
          cleaning_cycle?: number
          cleaning_date?: string | null
          cleaning_notes?: string | null
          cleaning_staff_id?: string | null
          completed_at?: string | null
          completion_notes?: string | null
          consegna_fee?: number
          consegna_staff_id?: string | null
          created_at?: string
          cribs?: number | null
          double_beds?: number | null
          extra_services_description?: string | null
          extra_services_price?: number | null
          id?: string
          is_urgent?: boolean | null
          order_number?: number | null
          pricing_mode?: string
          property_id: string
          real_guests?: number | null
          single_beds?: number | null
          sofa_beds?: number | null
          started_at?: string | null
          status?: string
          total_price?: number | null
          worked_minutes?: number | null
        }
        Update: {
          armchair_beds?: number | null
          bathrooms?: number | null
          bedrooms?: number | null
          bidets?: number | null
          checkin_at?: string | null
          checkout_at?: string | null
          cleaning_cycle?: number
          cleaning_date?: string | null
          cleaning_notes?: string | null
          cleaning_staff_id?: string | null
          completed_at?: string | null
          completion_notes?: string | null
          consegna_fee?: number
          consegna_staff_id?: string | null
          created_at?: string
          cribs?: number | null
          double_beds?: number | null
          extra_services_description?: string | null
          extra_services_price?: number | null
          id?: string
          is_urgent?: boolean | null
          order_number?: number | null
          pricing_mode?: string
          property_id?: string
          real_guests?: number | null
          single_beds?: number | null
          sofa_beds?: number | null
          started_at?: string | null
          status?: string
          total_price?: number | null
          worked_minutes?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "service_orders_cleaning_staff_id_fkey"
            columns: ["cleaning_staff_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_orders_consegna_staff_id_fkey"
            columns: ["consegna_staff_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_orders_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      custom_access_token_hook: { Args: { event: Json }; Returns: Json }
      get_monthly_stats: {
        Args: { target_month: string }
        Returns: {
          total_hours_worked: number
          total_properties: number
          total_revenue: number
        }[]
      }
      get_my_role: { Args: never; Returns: string }
      get_top_properties: {
        Args: { end_date: string; limit_count?: number; start_date: string }
        Returns: {
          os_count: number
          property_id: string
          property_name: string
        }[]
      }
      record_failed_login: {
        Args: { p_email_key: string; p_ip_key: string }
        Returns: {
          email_key: string
          failed_count: number
          ip_key: string
          last_failed_at: string
          locked_until: string
        }[]
      }
      save_property_atomic: {
        Args: {
          p_address?: string
          p_agency_id?: string
          p_armchair_beds?: number
          p_avg_cleaning_hours?: number
          p_base_price?: number
          p_bathrooms?: number
          p_bedrooms?: number
          p_bidets?: number
          p_client_type?: string
          p_cribs?: number
          p_double_beds?: number
          p_email?: string
          p_existing_agency_email?: string
          p_existing_owner_email?: string
          p_extra_per_person?: number
          p_max_guests?: number
          p_min_guests?: number
          p_name?: string
          p_new_agency_email?: string
          p_new_agency_name?: string
          p_new_owner_email?: string
          p_new_owner_name?: string
          p_notes?: string
          p_owner_id?: string
          p_phone?: string
          p_property_id?: string
          p_single_beds?: number
          p_sofa_beds?: number
          p_sqm_exterior?: number
          p_sqm_interior?: number
          p_sqm_total?: number
          p_zip_code?: string
          p_zone?: string
        }
        Returns: string
      }
      save_service_order_atomic: {
        Args: {
          p_armchair_beds?: number
          p_bathrooms?: number
          p_bedrooms?: number
          p_bidets?: number
          p_checkin_at?: string
          p_checkout_at?: string
          p_cleaning_date?: string
          p_cleaning_notes?: string
          p_cleaning_staff_ids?: string[]
          p_consegna_staff_id?: string
          p_cribs?: number
          p_double_beds?: number
          p_extra_services_description?: string
          p_extra_services_price?: number
          p_order_id?: string
          p_pricing_mode?: string
          p_property_id?: string
          p_real_guests?: number
          p_single_beds?: number
          p_sofa_beds?: number
          p_total_price?: number
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

